### ISSUE TITLE
Почему последовательность вопросов остается неизменной при любых ответах?

### ISSUE THREAD

**Issue by hugiron** [srogatch/ProbQA#1]
Привет. Собственно, вопрос в заголовке. Может стоит использовать корреляционную матрицу вопросов, чтобы не задавать те, на которые можно предсказать ответ (например, не спрашивать про пост-апокалипсис, если пользователь сказал, что игра не о будущем). И наоборот: выбирать вопросы, которые внесут большую ясность?

**Comment by srogatch** [comment]
Привет! Вообще говоря, последовательность вопросов может меняться. На каждом шаге, следующий вопрос выбирается случайно-взвешенным образом, где веса состоят из того, насколько хорошо данный вопрос разделяет цели на примерно равные части (а точнее, по минимум энтропии). Т.е. в принципе теория соответствует твоему предложению о "внесении наибольшей ясности". На практике же, при заполнении базы я начинал с немногих вопросов и немногих целей, поэтому получается что чем меньше номер вопроса, тем на больше игр он отвечен при тренировке. Поэтому движок и предпочитает вопросы с наименьшими номерами, когда они ещё не спрошены.

**Comment by hugiron** [comment]
То есть движок реализует Байесовский подход? Например, как [http://www.machinelearning.ru/wiki/images/7/78/BayesML-2010-Yangel-Akinator.pdf](тут).

**Comment by srogatch** [comment]
Да, что-то похожее. Не прочитал подробно эти слайды.
